# Generated by Django 5.0.3 on 2024-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='famousTemples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Temples')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('openingTime', models.TimeField()),
                ('closingTime', models.TimeField()),
                ('visit', models.BigIntegerField()),
                ('heading', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guide')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages')),
                ('location', models.CharField(max_length=100)),
                ('days', models.DurationField()),
                ('person', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('para', models.TextField(max_length=300)),
            ],
        ),
    ]
