# Generated by Django 5.0.3 on 2024-05-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_populardestinaion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='popularDestinaion',
        ),
    ]
