# Generated by Django 5.0.3 on 2024-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_populardestinaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famoustemples',
            name='heading',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='guide',
            name='experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packages',
            name='heading',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
