# Generated by Django 5.0.3 on 2024-05-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_famoustemples_heading_alter_guide_experience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='packages',
        ),
    ]
