# Generated by Django 5.0.3 on 2024-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages')),
                ('location', models.CharField(max_length=100)),
                ('days', models.DurationField()),
                ('search_name', models.CharField(max_length=100)),
                ('person', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heading', models.CharField(max_length=300)),
            ],
        ),
    ]
