# Generated by Django 5.0.3 on 2024-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='days',
            field=models.IntegerField(),
        ),
    ]
