# Generated by Django 5.0.3 on 2024-05-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_packages_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonial',
            new_name='testimonialModel',
        ),
    ]
