# Generated by Django 5.0.3 on 2024-05-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='famousTemples',
        ),
    ]
