# Generated by Django 5.0.3 on 2024-05-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_famoustemples'),
    ]

    operations = [
        migrations.CreateModel(
            name='famousTemples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Temples')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('search_name', models.CharField(max_length=100)),
                ('visit', models.BigIntegerField()),
                ('heading', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
