# Generated by Django 5.0.3 on 2024-05-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_nationalparks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutch_tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
