# Generated by Django 5.0.3 on 2024-05-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_kutch_tour_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='famousTemples',
        ),
    ]
