# Generated by Django 5.0.3 on 2024-06-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_famoustemples'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
