# Generated by Django 5.0.3 on 2024-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='file',
            field=models.ImageField(upload_to='bookingImage'),
        ),
    ]
