# Generated by Django 5.0.3 on 2024-06-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_booking_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
