# Generated by Django 5.0.3 on 2024-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=200)),
                ('file', models.ImageField(upload_to='bookingImage')),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
